apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rz81h1dpo-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rz81h1dpo-java-quarkus-gitops